### ISSUE TITLE
K05.webp misnamed...

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev-artwork-production#34]
While looking at spob space images I ran across K05 which is named as a K class (Mars-like) world and should therefore have little to no water... it appears to have almost as much water as the Earth (barren though the land looks) so it could probably do with being renamed N00 (for preference) or M14
I'd do it but I don't have the art repo set up (yet)... talking of which how should I go about getting a new F class planet space image into this repo? I could just attach it here if that'd work? but I think it's a .PSD file... need to double check, I've no access to it here. so I think this is the wrong repo? (All this has changed a lot since I last added artwork to Naev! :)

**Comment by bobbens** [comment]
> While looking at spob space images I ran across K05 which is named as a K class (Mars-like) world and should therefore have little to no water... it appears to have almost as much water as the Earth (barren though the land looks) so it could probably do with being renamed N00 (for preference) or M14 I'd do it but I don't have the art repo set up (yet).

I can look at it later, but it'll be a bit tricky because we have to do replacements for all usages of it.

>  talking of which how should I go about getting a new F class planet space image into this repo? I could just attach it here if that'd work? but I think it's a .PSD file... need to double check, I've no access to it here. so I think this is the wrong repo? (All this has changed a lot since I last added artwork to Naev! :)

So the way it works is you have to do a PR to submit the .psd file to the naev-artwork repository. Then render the image to lossless webp and do a PR here and add the necessary licensing information to gfx/ARTWORK_LICENSE. It's a bit complicated, but by separating data and engine, it gives us more flexibility to deal with large scale data changes without bloating the repo. We would use git-lfs to avoid this entire issue, but github tries to make you pay for that and it's not really feasible for naev.

**Comment by not-pyroman** [comment]
I think whoever named that one K05 may have named it such because the surface is like that of mars maybe? but I don't think an N class would fit either if it could support liquid water on the surface. I wonder why there are no N-class planet graphics though. I feel a reasonable option could be renaming to M14
